@startuml

class RegularPolygon {
    - n: int
    - side: double
    - x: double
    - y: double

    + RegularPolygon()
    + RegularPolygon(n: int, side: double)
    + RegularPolygon(n: int, side: double, x: double, y: double)
    + getN(): int
    + getSide(): double
    + getX(): double
    + getY(): double
    + getPerimeter(): double
    + getArea(): double
    + setN(n: int): void
    + setSide(side: double): void
    + setX(x: double): void
    + setY(y: double): void

}

@enduml